import type { Metadata } from "next";
import { Inter, Public_Sans } from "next/font/google";
import { Navbar } from "./components/navbar";
import {Footer} from "./components/footer";
import "./globals.css";



const inter = Inter({ subsets: ["latin"] });
const sans = Public_Sans({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${sans.variable}`}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
